#!/bin/sh

# This will go thru the HTML found in the given directory and run tidy on it

usage()
{
  echo "check html_dir"
  echo $1
  exit 1
}

if [ $# -eq 0 ] ; then
  usage "No arguments"
fi

HTML_DIR="$1"
if [ -z "$HTML_DIR" ] ; then
  usage "No html_dir"
fi

HTML_HOME=`cd "$HTML_DIR" && pwd`
if [ ! -d "${HTML_HOME}" ] ; then
  usage "No $HTML_HOME"
fi

`find $HTML_HOME -type f -name "*.html" -print0 | xargs -n 1 -t -0 tidy -q -utf8 -e`
