#!/bin/sh

usage()
{
    echo "itunes itunes.xml itunes.json"
    echo $1
    exit 1
}

if [ $# -eq 0 ] ; then
        usage "No arguments"
fi

if [ -n "$JAVA_HOME" ] ; then
    JAVA_CMD="$JAVA_HOME/bin/java"
else
    JAVA_CMD=`which java 2> /dev/null`
fi

PRG="$0"
PROG_HOME=`dirname "$PRG"`
PROG_HOME=`cd "$PROG_HOME" && pwd`

SITE_LIB_DIR="$PROG_HOME/lib"
if [ ! -d "${SITE_LIB_DIR}" ] ; then
    usage "Can't find ${SITE_LIB_DIR}"
fi

for i in "${SITE_LIB_DIR}" ; do
    for j in "${i}"/*.jar; do
        if [ -z "$LOCAL_CLASSPATH" ] ; then
            LOCAL_CLASSPATH="$j"
        else
            LOCAL_CLASSPATH="$LOCAL_CLASSPATH:$j"
        fi
    done
done

ITUNES_XML="$1"
if [ -z "$ITUNES_XML" ] ; then
    usage "No itunes.xml"
fi

ITUNES_JSON="$1"
if [ -z "$ITUNES_JSON" ] ; then
    usage "No itunes.json"
fi

COMMAND="exec \"$JAVA_CMD\" -Xms256m -Xmx256m -ea:com.bolsinga..."
if [ ! -z "$JAVA_OPTS" ] ; then
    COMMAND="$COMMAND $JAVA_OPTS"
fi
COMMAND="$COMMAND -classpath \"$LOCAL_CLASSPATH\" com.bolsinga.itunes.Main $ITUNES_XML $ITUNES_JSON"

if [ ! -z "$DUMP" ] ; then
    echo "$COMMAND"
    exit 0
fi

eval $COMMAND
