#!/bin/sh

usage()
{
    echo "itunes data_dir output_dir"
    echo $1
    exit 1
}

if [ $# -eq 0 ] ; then
        usage "No arguments"
fi

if [ -n "$JAVA_HOME" ] ; then
    JAVA_CMD="$JAVA_HOME/bin/java"
else
    JAVA_CMD=`which java 2> /dev/null`
fi

PRG="$0"
PROG_HOME=`dirname "$PRG"`
PROG_HOME=`cd "$PROG_HOME" && pwd`

SITE_LIB_DIR="$PROG_HOME/lib"
if [ ! -d "${SITE_LIB_DIR}" ] ; then
    usage "Can't find ${SITE_LIB_DIR}"
fi

for i in "${SITE_LIB_DIR}" ; do
    for j in "${i}"/*.jar; do
        if [ -z "$LOCAL_CLASSPATH" ] ; then
            LOCAL_CLASSPATH="$j"
        else
            LOCAL_CLASSPATH="$LOCAL_CLASSPATH:$j"
        fi
    done
done

DATA_DIR="$1"
if [ -z "$DATA_DIR" ] ; then
    usage "No data_dir"
fi

DATA_HOME=`cd "$DATA_DIR" && pwd`
if [ ! -d "${DATA_HOME}" ] ; then
    usage "No $DATA_HOME"
fi

OUTPUT_DIR="$2"
if [ -z "$OUTPUT_DIR" ] ; then
    usage "No output_dir"
fi
if [ ! -d "$OUTPUT_DIR" ] ; then
    mkdir -p "$OUTPUT_DIR"
fi
OUTPUT_HOME=`cd "$OUTPUT_DIR" && pwd`
if [ ! -d "${OUTPUT_HOME}" ] ; then
    usage "Can't find ${OUTPUT_HOME}"
fi

for i in "${DATA_HOME}/iTunes Music Library.xml"  "${DATA_HOME}/itunes-music-library.json" ; do
  if [ ! -f "$i" ] ; then
      usage "Can't find $i"
  fi
  DATA_FILES="$DATA_FILES \"$i\""
done

COMMAND="exec \"$JAVA_CMD\" -Xms256m -Xmx256m -ea:com.bolsinga..."
if [ ! -z "$JAVA_OPTS" ] ; then
    COMMAND="$COMMAND $JAVA_OPTS"
fi
COMMAND="$COMMAND -classpath \"$LOCAL_CLASSPATH\" com.bolsinga.itunes.Main $DATA_FILES $OUTPUT_HOME"

if [ ! -z "$DUMP" ] ; then
    echo "$COMMAND"
    exit 0
fi

eval $COMMAND
