#!/bin/sh

usage()
{
    echo "site data_dir output_dir user password  xml | musicxml | diaryxml | import | musicimport | diaryimport | site | musicsite | diarysite"
    echo $1
    exit 1
}

if [ $# -eq 0 ] ; then
        usage "No arguments"
fi

if [ -n "$JAVA_HOME" ] ; then
    JAVA_CMD="$JAVA_HOME/bin/java"
else
    JAVA_CMD=`which java 2> /dev/null`
fi

PRG="$0"
PROG_HOME=`dirname "$PRG"`
PROG_HOME=`cd "$PROG_HOME" && pwd`

SITE_LIB_DIR="$PROG_HOME/lib"
if [ ! -d "${SITE_LIB_DIR}" ] ; then
    usage "Can't find ${SITE_LIB_DIR}"
fi

for i in \
    "${SITE_LIB_DIR}" \
    "${SITE_LIB_DIR}/jwsdp-1_3/jaxb/lib" \
    "${SITE_LIB_DIR}/jwsdp-1_3/jwsdp-shared/lib" ; do
    for j in "${i}"/*.jar; do
        if [ -z "$LOCAL_CLASSPATH" ] ; then
            LOCAL_CLASSPATH="$j"
        else
            LOCAL_CLASSPATH="$LOCAL_CLASSPATH:$j"
        fi
    done
done

DATA_DIR="$1"
if [ -z "$DATA_DIR" ] ; then
    usage "No data_dir"
fi

DATA_HOME=`cd "$DATA_DIR" && pwd`
if [ ! -d "${DATA_HOME}" ] ; then
    usage "No $DATA_HOME"
fi

for i in \
    "${DATA_HOME}/iTunes Music Library.xml" \
    "${DATA_HOME}/shows.txt" \
    "${DATA_HOME}/venuemap.txt" \
    "${DATA_HOME}/bandsort.txt" \
    "${DATA_HOME}/relations.txt" \
    "${DATA_HOME}/comments.txt" \
    "${DATA_HOME}/statics.txt" \
    "${DATA_HOME}/diary.xml" \
    "${DATA_HOME}/music.xml" \
    "${DATA_HOME}/settings.xml" ; do
  if [ ! -f "$i" ] ; then
      usage "Can't find $i"
  fi
  DATA_FILES="$DATA_FILES \"$i\""
done

OUTPUT_DIR="$2"
if [ -z "$OUTPUT_DIR" ] ; then
    usage "No output_dir"
fi
if [ ! -d "$OUTPUT_DIR" ] ; then
    mkdir -p "$OUTPUT_DIR"
fi
OUTPUT_HOME=`cd "$OUTPUT_DIR" && pwd`
if [ ! -d "${OUTPUT_HOME}" ] ; then
    usage "Can't find ${OUTPUT_HOME}"
fi

if [ -z "$4" ] ; then
 ACTION="$3"
 if [ -z "$ACTION" ] ; then
     usage "No action"
 fi
 DB_USER="none";
 DB_PASSWORD="none";
else
 DB_USER="$3"
 if [ -z "$DB_USER" ] ; then
     usage "No db user"
 fi
 DB_PASSWORD="$4"
 if [ -z "$DB_PASSWORD" ] ; then
     usage "No db password"
 fi
 ACTION="$5"
 if [ -z "$ACTION" ] ; then
     usage "No action"
 fi
 TESTIMPORT=`echo $ACTION | sed -e's|import||'`
 if [ "$ACTION" = "$TESTIMPORT" ] ; then
     ACTION="$ACTION-db"
 fi
fi

COMMAND="exec \"$JAVA_CMD\" -Xms96m -Xmx96m"
if [ ! -z "$JAVA_OPTS" ] ; then
    COMMAND="$COMMAND \"$JAVA_OPTS\""
fi
COMMAND="$COMMAND -classpath \"$LOCAL_CLASSPATH\" com.bolsinga.site.Main $DATA_FILES $DB_USER $DB_PASSWORD $OUTPUT_HOME $ACTION"

if [ ! -z "$DUMP" ] ; then
    echo "$COMMAND"
    exit 0
fi

eval $COMMAND
