#!/bin/sh

usage()
{
  echo "upload site_dir ftp_password"
  echo $1
  exit 1
}

SITE_DIR=$1
if [ -z "$SITE_DIR" ] ; then
  usage "No site_dir."
fi
SITE_DIR=`cd "$SITE_DIR" && pwd`
if [ ! -d "${SITE_DIR}" ] ; then
  usage "No $SITE_DIR"
fi

FTP_PASSWORD=$2
if [ -z "$FTP_PASSWORD" ] ; then
  usage "No ftp_password."
fi

PRG="$0"
PROG_HOME=`dirname "$PRG"`
PROG_HOME=`cd "$PROG_HOME" && pwd`

ant -f $PROG_HOME/lib/upload.xml -Doutput.dir=$SITE_DIR -Dftp.user=bolsinga -Dftp.site=ftp.io.com -Dftp.password=$FTP_PASSWORD -Dftp.remote_dir=public-web upload
