#!/bin/sh

usage()
{
  echo "upload site_dir ftp_password <diary|all>"
  echo $1
  exit 1
}

SITE_DIR=$1
if [ -z "$SITE_DIR" ] ; then
  usage "No site_dir."
fi

SITE_TEST_DIR=`cd "$SITE_DIR" && pwd`
if [ ! -d "${SITE_TEST_DIR}" ] ; then
  usage "No $SITE_DIR"
fi

FTP_PASSWORD=$2
if [ -z "$FTP_PASSWORD" ] ; then
  usage "No ftp_password."
fi

TYPE=$3
if [ -z "$TYPE" ] ; then
  TYPE=upload
else
  if [ "$TYPE" = diary ] ; then
    TYPE=uploadDiary
  else
    if [ "$TYPE" = all ] ; then
      TYPE=upload
    else
      usage "Need to pass 'diary' or 'all'."
    fi
  fi
fi

PRG="$0"
PROG_HOME=`dirname "$PRG"`
PROG_HOME=`cd "$PROG_HOME" && pwd`

ant -f $PROG_HOME/lib/upload.xml -Doutput.dir=$SITEDIR -Dftp.password=$FTP_PASSWORD $TYPE
